# Generated by Django 3.1.3 on 2020-11-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMB_T', models.DecimalField(decimal_places=2, max_digits=4)),
                ('BOILER_T', models.DecimalField(decimal_places=2, max_digits=5)),
                ('COOL_FLOW', models.DecimalField(decimal_places=2, max_digits=5)),
                ('COOL_T_IN', models.DecimalField(decimal_places=2, max_digits=5)),
                ('COOL_T_OUT', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CURRENT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('E_ENERGY', models.DecimalField(decimal_places=1, max_digits=6)),
                ('E_POWER', models.DecimalField(decimal_places=1, max_digits=6)),
                ('HEAD_T_SET', models.DecimalField(decimal_places=2, max_digits=6)),
                ('HEAT_T_CON', models.DecimalField(decimal_places=2, max_digits=5)),
                ('HRAT_T_LIM', models.DecimalField(decimal_places=2, max_digits=5)),
                ('STATUS', models.SmallIntegerField()),
                ('VDTTM', models.BigIntegerField()),
                ('VOLTAGE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DATETIME', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
